// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1R_WkcvbAsTT1M1HR0a3JobYBkWN_QiE',
    appId: '1:766542695443:web:e572be9b2cb9887e3ac3e6',
    messagingSenderId: '766542695443',
    projectId: 'projectuas-769f1',
    authDomain: 'projectuas-769f1.firebaseapp.com',
    storageBucket: 'projectuas-769f1.appspot.com',
    measurementId: 'G-6PXR0Z0FM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7IpWYNnKOPhcpdR-91wBkz6M5WAtHAc',
    appId: '1:766542695443:android:fbf7e57154284f633ac3e6',
    messagingSenderId: '766542695443',
    projectId: 'projectuas-769f1',
    storageBucket: 'projectuas-769f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwgwQVSevIfhaWyewSFhv9TBXHWw4Qkc',
    appId: '1:766542695443:ios:47ff006c48b73acd3ac3e6',
    messagingSenderId: '766542695443',
    projectId: 'projectuas-769f1',
    storageBucket: 'projectuas-769f1.appspot.com',
    iosBundleId: 'com.example.uasEmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWwgwQVSevIfhaWyewSFhv9TBXHWw4Qkc',
    appId: '1:766542695443:ios:99bf27c9ab3a31203ac3e6',
    messagingSenderId: '766542695443',
    projectId: 'projectuas-769f1',
    storageBucket: 'projectuas-769f1.appspot.com',
    iosBundleId: 'com.example.uasEmoney.RunnerTests',
  );
}
